export const logo_Img = "https://logowik.com/content/uploads/images/restaurant9491.logowik.com.webp"
export const Best_Offer_Img = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_850,h_504/rng/md/carousel/production/"
export const Whats_On_Img = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const top_resto_img = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/"
export const resto_online_delivery = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const footer_Logo_img = "https://logowik.com/content/uploads/images/restaurant9491.logowik.com.webp"
export const restoMenu_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=17.4069559&lng=78.4610819&restaurantId="
